### ISSUE TITLE
Double livestream event error

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#679] opened 2021-02-14 15:50 UTC
This morning (Feb 14) there were 2 Sunday morning events displaying in the home page drop down menu (and after @GeorgeBellTMH told me to check Dynamo, it did show 2 events in Dynamo). However, on livestream admin, only 1 event displayed.

**Comment by JonEsparaz** [comment] 2021-02-14 21:21
@lucastbelem I'm looking at the DynamoDB table, I assume you deleted the second event? Almost impossible to postmortem without that data. 

Do you have details on the mysterious second event? Were the two events identical?

**Comment by lucastbelem** [comment] 2021-02-14 21:33
@JonEsparaz yeah, I had to delete it there so it wasn't confusing for people. It was nearly identical, but the live links were different. We were having issues on Friday with it, the events appeared not to be saving. But after logging out and logging back in, everything seemed fine. 
Maybe a weird glitch? I'll keep an eye and try and keep the event up next time.

**Comment by JonEsparaz** [comment] 2021-02-14 21:37
If there is a next time, you can delete the item, but first:
- select the item
- click the Actions dropdown
- export to .csv

**Comment by lucastbelem** [comment] 2021-02-14 21:40
Perfect! Thanks for letting me know!! I'll do that next time for sure.

**Comment by JonEsparaz** [comment] 2021-02-20 22:54
It appears this has happened again for 2021-02-21. DynamoDB export: https://gist.github.com/JonEsparaz/45f1d5d2384708190f0443460ecf9404

I figured out why the admin page and the frontend show different query results (fixed in https://github.com/themeetinghouse/web/pull/680).

Unsure if the root cause of the duplicates is a data entry issue or a bug.

**Comment by GeorgeBellTMH** [comment] 2021-02-22 22:26
Probably need to disable the create button once it's been clicked...

**Closed** 2021-02-27 00:40 UTC
Labels: admin, bug
