### ISSUE TITLE
Use WebP where possible instead of jpeg/png/gif

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#560] opened 2020-11-12 01:41 UTC
* [ ] Add a step to sharp() that writes a cached webp file alongside the jpeg/gif/png
* [ ] Update <scaledimage> to use the webp if the browser supports it

**Comment by JonEsparaz** [comment] 2020-11-12 02:15
Duplicate of #561.

**Closed by JonEsparaz** 2020-11-12 02:15 UTC
