### ISSUE TITLE
White header bar on mobile

### ISSUE THREAD

**Issue by lucastbelem** [themeetinghouse/web#187] opened 2020-05-05 14:47 UTC
When I visit certain pages like the COVID-19 update emergency page and click to watch a teaching video, a white header appears on the top of the page on mobile covering up both the logo and the X or hamburger menu. It makes it impossible to go back to the homepage. Can you look into this?

**Comment by JonEsparaz** [comment] 2020-05-05 15:41
Looking into this. Duplicate of #186.

**Closed** 2020-05-05 15:41 UTC
Labels: Priority 2
