### ISSUE TITLE
Videos not importing into admin

### ISSUE THREAD

**Issue by laurengermain** [themeetinghouse/web#916] opened 2022-02-02 16:29 UTC
Hey @GeorgeBellTMH this is a high priority now as this issue is happening for me (and Dan) every week.

I add the videos to the "Now Playing: Kids and Youth Teaching" YouTube playlist. Then in admin I hit the "Add All New" button and refresh the page. When I go back to the Import Video tab, the videos do not appear. Eventually, they import but it takes 1 day and overnight until they do.

This is happening consistently whenever I try to import the Sunday teaching, teaching highlight, livestream, and the Kids and Youth weekly videos.

Specific videos from this week listed in this doc:
https://docs.google.com/spreadsheets/d/1WMDLTv0-fCk3Y_S_Bjrk95ozPidfnd-liJrCS1T5vKY/edit#gid=0

[Screen Shot 2022-02-02 at 11 16 38 AM](https://user-images.githubusercontent.com/89869101/152193514-a200dea2-64c2-41b9-82fe-0f6803e8f1f2.png)

**Comment by lucastbelem** [comment] 2022-02-02 16:48
@JonEsparaz if you're available and interested, this is high priority for us right now and there are some current cases in the spreadsheet. Totally get it if you don't have time :)

**Comment by GeorgeBellTMH** [comment] 2022-02-02 17:25
I’m going to add more playlists to the ignore list…I think we might be hitting the api limits again….should speed things up as well…

**Comment by JonEsparaz** [comment] 2022-02-02 19:04
> @JonEsparaz if you're available and interested, this is high priority for us right now and there are some current cases in the spreadsheet. Totally get it if you don't have time :)

@lucastbelem unfortunately I'm don't have the capacity 😔

**Comment by GeorgeBellTMH** [comment] 2022-02-03 02:16
I've updated the playlist ignore list...should be much faster now...hopefully that will resolve the issues...I will test tomorrow when the limits reset themselves...

**Comment by lucastbelem** [comment] 2022-02-04 02:40
@JonEsparaz no worries. Thanks for getting back to me :)

**Comment by lucastbelem** [comment] 2022-02-04 02:40
@laurengermain could you pls test? Did the videos import?

**Comment by laurengermain** [comment] 2022-02-04 17:24
@lucastbelem the videos imported yesterday. However, I tried importing the youth video and it hasn't come into admin today.

https://www.youtube.com/watch?v=EkG1-fTxrRQ&list=PLB5r2P47beqKcw--wi3iCdP-i_Ksnx_9-&index=5

**Comment by lucastbelem** [comment] 2022-02-04 18:15
@GeorgeBellTMH can you pls investigate?

**Comment by GeorgeBellTMH** [comment] 2022-02-05 19:17
Ok...so it's because it's a premiere...so it's not technically live yet...

**Comment by GeorgeBellTMH** [comment] 2022-02-05 19:18
The website was built before premiere's existed...so it doesn't know about them...we'd have to figure out how to deal with them and then figure out how they show up on the web and app...

For now, just import it after the premiere has passed...

**Comment by GeorgeBellTMH** [comment] 2022-02-05 19:21
(or change it to not a premiere)

**Comment by GeorgeBellTMH** [comment] 2022-02-05 19:22
@lucastbelem let me know how you want to prioritize this...maybe there is some time for a bunch of video importing improvements?

**Comment by GeorgeBellTMH** [comment] 2022-02-05 19:39
Ok...update...that video is under The Meeting House Youth: https://www.youtube.com/channel/UCPvZFkiTYVEbKAsoIXid9jg which is a separate channel from The Meeting House: https://www.youtube.com/c/themeetinghousechurch

**Comment by GeorgeBellTMH** [comment] 2022-02-05 19:46
We need to bring that youth channel under our brand account...https://support.google.com/youtube/answer/3056283?hl=en

**Comment by GeorgeBellTMH** [comment] 2022-02-05 19:47
(we need to do the second section Move your channel to another Brand Account associated with the same Google Account)

**Comment by GeorgeBellTMH** [comment] 2022-02-05 19:53
If you want we can do this on zoom on Monday...

**Comment by lucastbelem** [comment] 2022-02-06 01:03
@GeorgeBellTMH ok yeah let's figure this out this week...the weird thing is that it's been a premiere for a few weeks, but this is the first time that it hasn't worked. And my understanding is that it's always in the youth channel.

**Comment by lucastbelem** [comment] 2022-02-06 14:32
@GeorgeBellTMH I uploaded the video to the TMH youtube channel and still no luck. :(

**Comment by lucastbelem** [comment] 2022-02-08 21:28
Just flagging that this issue is still live. We need to solve this before Thursday so everything is up for Sunday.

**Comment by GeorgeBellTMH** [comment] 2022-02-10 03:27
Ok take a look...I think it's working now...

**Comment by lucastbelem** [comment] 2022-02-10 16:04
@GeorgeBellTMH this is somewhat resolved. The videos imported, but other things broke...we can edit metadata, can't see anything in a category (i.e. adult teaching), and the latest teaching component is gone from the teaching page.

**Comment by GeorgeBellTMH** [comment] 2022-02-10 18:15
Fix is publishing now...

**Comment by lucastbelem** [comment] 2022-02-14 19:22
Duplicate of #920

**Closed by lucastbelem** 2022-02-14 19:22 UTC
