### ISSUE TITLE
One Story upcoming series link not working

### ISSUE THREAD

**Issue by laurengermain** [themeetinghouse/web#1025] opened 2022-06-30 15:34 UTC
@GeorgeBellTMH @lucastbelem I've updated the series cards on the platform so that the series for July and August are now listed as current and upcoming series... Everything is working aside from the Jr High Midweek (The Look of Love) url.

I copy it directly from the Midweek series page but whenever I paste it into the new card or go to the link, it redirects to the Jr High Weekend page. We had this issue once before, not sure what we did to resolve it. But this needs to be fixed ASAP as a lot of curriculum users are waiting to download the materials for August.

The Look of Love Jr High Weekend url: https://beta.jesuscollective.com/web/resourcedisplay/resource-1611326161952?resource=00adbc2d-53e4-4cda-a14a-d7cc923f0d1b&series=826fc67b-803d-47c5-bc0f-c38320675488

The Look of Love Jr High Midweek url: https://beta.jesuscollective.com/web/resourcedisplay/resource-1611326161952?resource=00adbc2d-53e4-4cda-a14a-d7cc923f0d1b&series=826fc67b-803d-47c5-bc0f-c38320675488 (Should display what's in the attached screenshot).

![Screen Shot 2022-06-30 at 11 27 10 AM](https://user-images.githubusercontent.com/89869101/176717218-b6b488c6-46a5-4239-ba17-adcf72f4874c.png)

The series cards affected are on the main overview page and the Jr High Midweek page at the top. Clicking on the series in the Year 2 carousel works, and that's where I'm grabbing the url from.

Thanks!

**Comment by lucastbelem** [comment] 2022-06-30 16:32
@GeorgeBellTMH Something is going on here George. We've always copied urls from the series page to do this, but actually, any resource I click displays the same url.

@laurengermain I'm trying to find the workaround we did last time. Will let you know as soon as I figure it out.

**Comment by GeorgeBellTMH** [comment] 2022-07-06 20:36
I can't replicate this, please let me know if still a problem...I am closing for now...

**Comment by lucastbelem** [comment] 2022-07-08 16:30
@GeorgeBellTMH I checked this out and it's definitely occurring. If you definitely can't see it, it might an issue tied to specific users. Otherwise, here is what the issue is:

The url generated for the series Lauren needs (Jr. High Midweek "Look of Love III") is the SAME as the url for another series (Jr. High Weekend "Look of Love III"). That's why it's going to the wrong place. Not because Lauren is pasting the wrong series. But because the correct series' url is showing as the same as the wrong one. Can you pls see if you can address this asap?

**Comment by georgevicbell** [comment] 2022-07-09 04:23
I think this is a problem when you get the url…I think maybe refresh the page and go to it and the url should be correct. Or try to get to the page from another way...

George

On Jul 8, 2022, at 9:30 AM, Lucas Belem ***@***.******@***.***>> wrote:



@GeorgeBellTMH<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGeorgeBellTMH&data=05%7C01%7C%7C3c76852cdf224a36f41e08da60ff3ad7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637928946627866395%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=epBzSHrMI6lB4YdlBwxXZJpK1oHY2XEENrGWLkgeMIM%3D&reserved=0> I checked this out and it's definitely occurring. If you definitely can't see it, it might an issue tied to specific users. Otherwise, here is what the issue is:

The url generated for the series Lauren needs (Jr. High Midweek "Look of Love III") is the SAME as the url for another series (Jr. High Weekend "Look of Love III"). That's why it's going to the wrong place. Not because Lauren is pasting the wrong series. But because the correct series' url is showing as the same as the wrong one. Can you pls see if you can address this asap?

**Comment by laurengermain** [comment] 2022-07-28 19:30
Hey @GeorgeBellTMH @lucastbelem just checking in on this as it still seems to be an issue for The Look of Love series -- it's now in the "Current Series" cards on the platform for August.

I swapped the "Upcoming Series" cards for September (Genesis Joseph) and did not encounter the same issue; all is working for that series.

**Comment by lucastbelem** [comment] 2022-08-02 14:35
@GeorgeBellTMH I'd like to look at this today. I'll book a short meeting for us. @laurengermain can you join us today at 2pm ET? May be best if you're there to walk us through the problem.

**Comment by lucastbelem** [comment] 2023-01-26 14:33
@laurengermain this was for JC, but did it get solved?

**Comment by laurengermain** [comment] 2023-01-27 14:48
@lucastbelem I'm not sure if this got resolved, but there's no way to test it anymore since there are new series in the cards on the Overview page. It wasn't occurring for every series, just The Look of Love.

**Closed** 2023-04-26 19:55 UTC
