### ISSUE TITLE
Add SSL/TLS to beta.themeetinghouse.com via Amazon

### ISSUE THREAD

**Issue by GeorgeBellTMH** [themeetinghouse/web#11] opened 2019-02-26 15:28 UTC
Branden will need to add the cert to amazon.

**Comment by branden-eyk** [comment] 2019-03-15 14:01
Took awhile thanks to Digicert deciding we need to be validated again, but a duplicate of our wildcard certificate for themeetinghouse.com has been imported into Amazon AWS's certificate manager.

**Closed** 2019-08-02 04:49 UTC
Labels: infrastructure
